[general]
GEMINI_API_KEY = "your_actual_gemini_api_key_here"

# Optional: Add more configuration
[database]
DB_URL = "your_database_url"

[notifications]
WEBHOOK_URL = "your_webhook_url"
EMAIL_SERVICE = "your_email_service"
